"""add healthcare and entertainment scores

Revision ID: c5c71adf0304
Revises: a1b2c3d4e5f6
Create Date: 2026-04-01 09:53:21.016890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c71adf0304'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comfort_scores', sa.Column('healthcare_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('comfort_scores', sa.Column('entertainment_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.create_index('idx_properties_active', 'properties', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_properties_partner', 'properties', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_properties_partner', table_name='properties')
    op.drop_index('idx_properties_active', table_name='properties', postgresql_where=sa.text('is_active = true'))
    op.drop_column('comfort_scores', 'entertainment_score')
    op.drop_column('comfort_scores', 'healthcare_score')
    # ### end Alembic commands ###
